-- Add missing values to the audit enums without dropping existing data.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VERIFY';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VERIFY_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RSVP_SUBMIT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPORT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT';

ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'AUTH';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'SYSTEM';
